development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:960f499eb8ade0c6f1af618c35a89196@dory.redistogo.com:10417/
  channel_prefix: instatalk_production
